// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5d-4qs4LHN9uXMxL9ISgeEz1PL2-eR_8',
    appId: '1:213714918492:web:c70c222ecf684d744c9a99',
    messagingSenderId: '213714918492',
    projectId: 'todolist-4cfbc',
    authDomain: 'todolist-4cfbc.firebaseapp.com',
    storageBucket: 'todolist-4cfbc.firebasestorage.app',
    measurementId: 'G-P5B10C8FMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZGRsNnxTMHcW0PePfJUPKoFNNDw-jPlI',
    appId: '1:213714918492:android:f39be7583b1fa1504c9a99',
    messagingSenderId: '213714918492',
    projectId: 'todolist-4cfbc',
    storageBucket: 'todolist-4cfbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9vHk_9S3YNqMVBgvR6luzHNisIkNG_WI',
    appId: '1:213714918492:ios:b4263030de8160f14c9a99',
    messagingSenderId: '213714918492',
    projectId: 'todolist-4cfbc',
    storageBucket: 'todolist-4cfbc.firebasestorage.app',
    iosClientId: '213714918492-bmpn4bq48gdh87teg1tdi4ugpqdv6f23.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9vHk_9S3YNqMVBgvR6luzHNisIkNG_WI',
    appId: '1:213714918492:ios:b4263030de8160f14c9a99',
    messagingSenderId: '213714918492',
    projectId: 'todolist-4cfbc',
    storageBucket: 'todolist-4cfbc.firebasestorage.app',
    iosClientId: '213714918492-bmpn4bq48gdh87teg1tdi4ugpqdv6f23.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5d-4qs4LHN9uXMxL9ISgeEz1PL2-eR_8',
    appId: '1:213714918492:web:87cb09060b5bf4544c9a99',
    messagingSenderId: '213714918492',
    projectId: 'todolist-4cfbc',
    authDomain: 'todolist-4cfbc.firebaseapp.com',
    storageBucket: 'todolist-4cfbc.firebasestorage.app',
    measurementId: 'G-PE3X1MF6LE',
  );
}
